# Basics of Numpy

NumPy is a popular library in Python for scientific and mathematical calculations.

In [37]:
# import numpy package

import numpy as np

In [38]:
# create a 1-D array
one_dim_array = np.array([1, 2, 3])
print(one_dim_array)

[1 2 3]


### Can this array have multiple data types?

In [39]:
multiple_dtype_array = np.array([51, "Apples", True])
print(multiple_dtype_array)
print(multiple_dtype_array.dtype)

['51' 'Apples' 'True']
<U21


In [40]:
multiple_dtype_array = np.array([51, "Apples", True], dtype=int)
print(multiple_dtype_array.dtype)
print(multiple_dtype_array)

ValueError: invalid literal for int() with base 10: 'Apples'

## NumPy Arrays and different methods

In [ ]:
a = np.array([2, 4, 8])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[2 4 8]


## arange()
- start : inclusive
- end : exlusive

In [ ]:
# Create an array with 10 elements starting from 0
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# create an array strating from 1, ending at 9, incremented by 2
c = np.arange(1, 10, 2)
print(c)

[1 3 5 7 9]


## linspace(x, y, z)
creates z elements evenly spaced between x and y

In [ ]:
linear_spaced_array = np.linspace(0, 100, 5)
print(linear_spaced_array)

[  0.  25.  50.  75. 100.]


In [ ]:
linear_spaced_array_int = np.linspace(0, 100, 5, dtype=int)
print(linear_spaced_array_int)

[  0  25  50  75 100]


# More ways of creating arrays

In [ ]:
ones_arrays = np.ones(3)
print(ones_arrays)

[1. 1. 1.]


In [ ]:
zeros_arrays = np.zeros(5)
print(zeros_arrays)

[0. 0. 0. 0. 0.]


In [ ]:
empty_arrays = np.empty(5)
print(empty_arrays)

[0. 0. 0. 0. 0.]


np.zeros() initialises with all 0s, while np.empty() initialises an empty array and values might be just garbage values, although it printed 0 above. 

In [ ]:
# random values between 0 and 1
random_arrays = np.random.rand(5)
print(random_arrays)

[0.41800859 0.84514266 0.88626732 0.22738712 0.27109694]


# Multidimensional Arrays
as numpy array is called ndarray, lets look at how easy it is to create multi dimensional arrays and perform calculations on them.

In [42]:
multi_dim_array = np.array([[1, 2, 3], [2, 3, 5], [8, 7, 9]])
print(multi_dim_array)
print(multi_dim_array.dtype)

[[1 2 3]
 [2 3 5]
 [8 7 9]]
int64


We can also reshape an existing array into a different dimesnion using reshape()

In [ ]:
one_dim_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = np.reshape(one_dim_array, (2, 3))

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
one_dim_array = np.arange(7) # 7 elements
print(one_dim_array) 

# reshaped_array = np.reshape(one_dim_array, (2, 3))
# This will throw an error

[0 1 2 3 4 5 6]


# Size, shape and dimension of array

In [ ]:
one_dim_array.ndim

1

In [43]:
print(multi_dim_array)
print(multi_dim_array.ndim)

[[1 2 3]
 [2 3 5]
 [8 7 9]]
2


In [44]:
ab = np.array([[1, 2, 3], [4, 5, 6]])
print(ab)
print(ab.ndim)

[[1 2 3]
 [4 5 6]]
2


In [45]:
ab.shape

(2, 3)

In [46]:
ab.size

6

# Maths
The real fun and also the power of Numpy is the way it helps in maths between the numpy arrays. Its simple, fast and elegent. Lets see how!

In [53]:
arr_1 = np.array([2, 3, 5])
arr_2 = np.array([6, 2, 8])

addition = arr_1 + arr_2
print(addition)

subtraction = arr_1 - arr_2
print(subtraction)

multiplication = arr_1 * arr_2
print(multiplication)

[ 8  5 13]
[-4  1 -3]
[12  6 40]


## Broadcasting

We can multiply a scalar with a vector. Useful in situations when we have a large dataset and lets say we want to convert the data by multiplying some scalar e.g. kgs to grams (* 1000)

In [58]:
weights_in_kgs = np.arange(1, 10)
print(weights_in_kgs)

# convert into grams
weights_in_grams = weights_in_kgs * 1000
print(weights_in_grams)

# lets also add 100 gms to each weight
weights_in_grams_100 = weights_in_grams + 100
print(weights_in_grams_100)

[1 2 3 4 5 6 7 8 9]
[1000 2000 3000 4000 5000 6000 7000 8000 9000]
[1100 2100 3100 4100 5100 6100 7100 8100 9100]


# Indexing and Slicing

## Indexing

In [60]:
two_dim_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(two_dim_array[0])
print(two_dim_array[1][2])

[1 2 3]
6


## Slicing

array[start:end:step]

- start is inclusive, defaults to 0
- end is exclusive, defaults to (len - 1)
- step is by default 1

In [65]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:2])
print(arr[1:])
print(arr[:])
print(arr[:3])
print(arr[::2])

[2]
[2 3 4 5]
[1 2 3 4 5]
[1 2 3]
[1 3 5]


In [71]:
# all of these will be equal
print(arr == arr[:] == arr[::])

True


In [78]:
# Slicing a multi dim array

print(two_dim_array)
print(two_dim_array[:1])
print(two_dim_array[:1, :1])
print(two_dim_array[1:2])
print(two_dim_array[:, :1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1]]
[[4 5 6]]
[[1]
 [4]
 [7]]


# Stacking
We can stack arrays horizontally or vertically 

In [79]:
arr_1 = np.array([[1, 1], [2, 2]])
arr_2 = np.array([[3, 3], [4, 4]])
print(arr_1)
print(arr_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [81]:
# Stack the arrays
vertical_stack = np.vstack((arr_1, arr_2))
print(vertical_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [82]:
horizontal_stack = np.hstack((arr_1, arr_2))
print(horizontal_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [85]:
arr_3 = np.array([[1, 2, 3], [4, 5, 6]])

# This will throw an Error
# vertical_stack = np.vstack((arr_1, arr_3))
# print(vertical_stack)