# Basics of Numpy

NumPy is a popular library in Python for scientific and mathematical calculations.

In [ ]:
# import numpy package

import numpy as np

In [5]:
# create a 1-D array
one_dim_array = np.array([1, 2, 3])
print(one_dim_array)

[1 2 3]


### Can this array have multiple data types?

In [8]:
multiple_dtype_array = np.array([51, "Apples", True])
print(multiple_dtype_array)
print(multiple_dtype_array.dtype)

['51' 'Apples' 'True']
<U21


In [9]:
multiple_dtype_array = np.array([51, "Apples", True], dtype=int)
print(multiple_dtype_array.dtype)
print(multiple_dtype_array)

ValueError: invalid literal for int() with base 10: 'Apples'

## NumPy Arrays and different methods

In [12]:
a = np.array([2, 4, 8])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[2 4 8]


## arange()
- start : inclusive
- end : exlusive

In [ ]:
# Create an array with 10 elements starting from 0
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# create an array strating from 1, ending at 9, incremented by 2
c = np.arange(1, 10, 2)
print(c)

[1 3 5 7 9]


## linspace(x, y, z)
creates z elements evenly spaced between x and y

In [16]:
linear_spaced_array = np.linspace(0, 100, 5)
print(linear_spaced_array)

[  0.  25.  50.  75. 100.]


In [17]:
linear_spaced_array_int = np.linspace(0, 100, 5, dtype=int)
print(linear_spaced_array_int)

[  0  25  50  75 100]


# More ways of creating arrays

In [21]:
ones_arrays = np.ones(3)
print(ones_arrays)

[1. 1. 1.]


In [23]:
zeros_arrays = np.zeros(5)
print(zeros_arrays)

[0. 0. 0. 0. 0.]


In [24]:
empty_arrays = np.empty(5)
print(empty_arrays)

[0. 0. 0. 0. 0.]


np.zeros() initialises with all 0s, while np.empty() initialises an empty array and values might be just garbage values, although it printed 0 above. 

In [ ]:
# random values between 0 and 1
random_arrays = np.random.rand(5)
print(random_arrays)

[0.41800859 0.84514266 0.88626732 0.22738712 0.27109694]
